name: test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.24.1
      with:
        elixir-version: 1.20.3
        otp-version: 29.0

    - name: Install dependencies
      run: mix deps.get

    - name: Check dependencies
      run: mix deps.unlock --check-unused

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Compile without warnings
      run: mix compile --warnings-as-errors

    - name: Build documentation
      run: mix docs --warnings-as-errors

  mix_test:
    name: mix test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})

    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.14.3
            otp: 25.1
          - elixir: 1.20.3
            otp: 29.0
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.24.1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}

    - name: Install dependencies
      run: mix deps.get --only test

    - name: Run tests
      run: mix test --warnings-as-errors
